"""initial

Revision ID: 2036ab5a6eab
Revises: 
Create Date: 2026-06-15 12:21:27.801313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2036ab5a6eab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schedules_owner_id'), ['owner_id'], unique=False)

    op.create_table('availability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('specific_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_availability_schedule_id'), ['schedule_id'], unique=False)

    op.create_table('event_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('slot_interval', sa.Integer(), nullable=False),
    sa.Column('minimum_booking_notice', sa.Integer(), nullable=False),
    sa.Column('before_event_buffer', sa.Integer(), nullable=False),
    sa.Column('after_event_buffer', sa.Integer(), nullable=False),
    sa.Column('requires_confirmation', sa.Boolean(), nullable=False),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_event_type_owner_slug')
    )
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_types_owner_id'), ['owner_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_types_schedule_id'), ['schedule_id'], unique=False)

    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uid', sa.String(length=32), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('responses', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bookings_event_type_id'), ['event_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_start_time'), ['start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_bookings_uid'), ['uid'], unique=True)

    op.create_table('attendees',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('time_zone', sa.String(length=64), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['bookings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attendees_booking_id'), ['booking_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attendees_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attendees', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attendees_email'))
        batch_op.drop_index(batch_op.f('ix_attendees_booking_id'))

    op.drop_table('attendees')
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bookings_uid'))
        batch_op.drop_index(batch_op.f('ix_bookings_status'))
        batch_op.drop_index(batch_op.f('ix_bookings_start_time'))
        batch_op.drop_index(batch_op.f('ix_bookings_event_type_id'))

    op.drop_table('bookings')
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_types_schedule_id'))
        batch_op.drop_index(batch_op.f('ix_event_types_owner_id'))

    op.drop_table('event_types')
    with op.batch_alter_table('availability', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_availability_schedule_id'))

    op.drop_table('availability')
    with op.batch_alter_table('schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_schedules_owner_id'))

    op.drop_table('schedules')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
